"""City information for soccer teams across different leagues."""

CITY_DATA = {
    # Argentine Primera División
    'arg.1': {
        'River Plate': 'Buenos Aires',
        'Boca Juniors': 'Buenos Aires',
        'Racing Club': 'Avellaneda',
        'San Lorenzo': 'Buenos Aires',
        'Independiente': 'Avellaneda',
        'Estudiantes': 'La Plata',
        'Estudiantes de La Plata': 'La Plata',
        'Belgrano': 'Córdoba',
        'Central Córdoba': 'Santiago del Estero',
        'Unión': 'Santa Fe',
        'Argentinos Juniors': 'Buenos Aires',
        'Newell\'s Old Boys': 'Rosario',
        'Rosario Central': 'Rosario',
        'Vélez Sarsfield': 'Buenos Aires',
        'Lanús': 'Lanús',
        'Talleres': 'Córdoba',
        'Banfield': 'Banfield',
        'Gimnasia La Plata': 'La Plata',
        'Defensa y Justicia': 'Florencio Varela',
        'Instituto': 'Córdoba',
        'Sarmiento': 'Junín',
        'Tigre': 'Victoria',
        'Barracas Central': 'Buenos Aires',
        'Platense': 'Florida',
        'Colón': 'Santa Fe',
        'Arsenal': 'Sarandí',
        'Arsenal Sarandi': 'Sarandí',
        'Huracán': 'Buenos Aires',
        'Godoy Cruz': 'Godoy Cruz',
        'Atlético Tucumán': 'San Miguel de Tucumán',
        'Aldosivi': 'Mar del Plata',
        'Independiente Rivadavia': 'Mendoza',
        'Belgrano (Córdoba)': 'Córdoba',
        'Central Córdoba (Santiago del Estero)': 'Santiago del Estero',
        'Unión (Santa Fe)': 'Santa Fe'
    },
    
    # Argentine Primera Nacional
    'arg.2': {
        'Alvarado': 'Mar del Plata',
        'Alvarado (Mar del Plata)': 'Mar del Plata',
        'Gimnasia y Tiro': 'Salta',
        'Gimnasia y Tiro (Salta)': 'Salta',
        'Racing': 'Córdoba',
        'Racing (Córdoba)': 'Córdoba',
        'San Martín': 'Tucumán',
        'San Martín (Tucumán)': 'Tucumán',
        'Agropecuario': 'Carlos Casares',
        'All Boys': 'Floresta',
        'Almirante Brown': 'Isidro Casanova',
        'Atlanta': 'Buenos Aires',
        'Brown de Adrogué': 'Adrogué',
        'Chacarita Juniors': 'Villa Maipú',
        'Chaco For Ever': 'Resistencia',
        'Defensores de Belgrano': 'Buenos Aires',
        'Deportivo Madryn': 'Puerto Madryn',
        'Deportivo Maipú': 'Maipú',
        'Deportivo Morón': 'Morón',
        'Estudiantes de Río Cuarto': 'Río Cuarto',
        'Ferro Carril Oeste': 'Buenos Aires',
        'Gimnasia Mendoza': 'Mendoza',
        'Guillermo Brown': 'Puerto Madryn',
        'Independiente Rivadavia': 'Mendoza',
        'Mitre': 'Santiago del Estero',
        'Quilmes': 'Quilmes',
        'San Martín San Juan': 'San Juan',
        'Temperley': 'Temperley',
        'Tristán Suárez': 'Tristán Suárez',
        'Villa Dálmine': 'Campana',
        'Almagro': 'José Ingenieros',
        'Colegiales': 'Buenos Aires',
        'Güemes': 'Santiago del Estero',
        'Los Andes': 'Lomas de Zamora',
        'Patronato': 'Paraná',
        'San Miguel': 'San Miguel',
        'Arsenal Sarandi': 'Sarandí'
    },
    
    # Australian A-League
    'aus.1': {
        'Adelaide United': 'Adelaide',
        'Brisbane Roar': 'Brisbane',
        'Central Coast Mariners': 'Gosford',
        'Macarthur FC': 'Sydney',
        'Melbourne City': 'Melbourne',
        'Melbourne City FC': 'Melbourne',
        'Melbourne Victory': 'Melbourne',
        'Newcastle Jets': 'Newcastle',
        'Perth Glory': 'Perth',
        'Sydney FC': 'Sydney',
        'Wellington Phoenix': 'Wellington',
        'Wellington Phoenix FC': 'Wellington',
        'Western Sydney Wanderers': 'Sydney',
        'Western United': 'Melbourne',
        'Auckland FC': 'Auckland'
    },
    
    # Austrian Bundesliga
    'aut.1': {
        'Austria Vienna': 'Vienna',
        'LASK Linz': 'Linz',
        'RB Salzburg': 'Salzburg',
        'Rapid Vienna': 'Vienna',
        'SC Rheindorf Altach': 'Altach',
        'SK Sturm Graz': 'Graz',
        'TSV Hartberg': 'Hartberg',
        'WSG Swarovski Tirol': 'Innsbruck',
        'Wolfsberger': 'Wolfsberg',
        'Grazer AK': 'Graz',
        'SK Austria Klagenfurt': 'Klagenfurt',
        'FC Blau-Weiß Linz': 'Linz',
    },
    
    # Belgian Pro League
    'bel.1': {
        'Anderlecht': 'Brussels',
        'Beerschot': 'Antwerp',
        'Dender': 'Denderleeuw',
        'KAA Gent': 'Ghent',
        'KV Kortrijk': 'Kortrijk',
        'KV Mechelen': 'Mechelen',
        'KVC Westerlo': 'Westerlo',
        'Oud-Heverlee Leuven': 'Leuven',
        'Racing Genk': 'Genk',
        'Royal Charleroi SC': 'Charleroi',
        'Sint-Truidense': 'Sint-Truiden',
        'Standard Liege': 'Liège',
        'Union St.-Gilloise': 'Brussels',
        'Antwerp': 'Antwerp',
        'Cercle Brugge KSV': 'Bruges',
        'Club Brugge': 'Bruges',
    },
    
    # Belgian First Division B
    'bel.2': {
        "Beerschot": "Antwerp",
        "Club NXT": "Bruges",
        "Deinze": "Deinze",
        "Dender": "Denderleeuw",
        "FC Luik": "Liège",
        "Francs Borains": "Boussu",
        "KV Oostende": "Ostend",
        "Lommel SK": "Lommel",
        "Patro Eisden": "Maasmechelen",
        "RFC Seraing": "Seraing",
        "SK Beveren": "Beveren",
        "Zulte Waregem": "Waregem",
    },
    
    # Brazilian Série A
    'bra.1': {
        'Atlético-MG': 'Belo Horizonte',
        'Bahia': 'Salvador',
        'Botafogo': 'Rio de Janeiro',
        'Ceará': 'Fortaleza',
        'Corinthians': 'São Paulo',
        'Cruzeiro': 'Belo Horizonte',
        'Flamengo': 'Rio de Janeiro',
        'Fluminense': 'Rio de Janeiro',
        'Fortaleza': 'Fortaleza',
        'Grêmio': 'Porto Alegre',
        'Internacional': 'Porto Alegre',
        'Mirassol': 'Mirassol',
        'Palmeiras': 'São Paulo',
        'Red Bull Bragantino': 'Bragança Paulista',
        'Santos': 'Santos',
        'São Paulo': 'São Paulo',
        'Sport': 'Recife',
        'Vasco da Gama': 'Rio de Janeiro',
        'Vitória': 'Salvador',
        'Juventude': 'Caxias do Sul',
    },
    
    # Brazilian Série B
    'bra.2': {
        'Amazonas': 'Manaus',
        'América-MG': 'Belo Horizonte',
        'Athletic Club (Minas Gerais)': 'São João del Rei',
        'Athletico-PR': 'Curitiba',
        'Atlético-GO': 'Goiânia',
        'Avaí': 'Florianópolis',
        'Botafogo SP': 'Ribeirão Preto',
        'Chapecoense': 'Chapecó',
        'Coritiba': 'Curitiba',
        'CRB': 'Maceió',
        'Criciúma': 'Criciúma',
        'Cuiabá': 'Cuiabá',
        'Ferroviária': 'Araraquara',
        'Goiás': 'Goiânia',
        'Novorizontino': 'Novo Horizonte',
        'Operario PR': 'Ponta Grossa',
        'Paysandu': 'Belém',
        'Remo': 'Belém',
        'Vila Nova-GO': 'Goiânia',
        'Volta Redonda': 'Volta Redonda',
    },
    
    # Chinese Super League
    'chn.1': {
        'Shanghai Port': 'Shanghai',
        'Shanghai Shenhua': 'Shanghai',
        'Beijing Guoan': 'Beijing',
        'Shandong Taishan': 'Jinan',
        'Chengdu Rongcheng': 'Chengdu',
        'Zhejiang': 'Hangzhou',
        'Zhejiang Professional FC': 'Hangzhou',
        'Tianjin Jinmen Tiger': 'Tianjin',
        'Changchun Yatai': 'Changchun',
        'Henan': 'Zhengzhou',
        'Henan Songshan Longmen': 'Zhengzhou',
        'Meizhou Hakka': 'Meizhou',
        'Qingdao Hainiu': 'Qingdao',
        'Qingdao West Coast': 'Qingdao',
        'Shenzhen': 'Shenzhen',
        'Shenzhen Xinpengcheng': 'Shenzhen',
        'Nantong Zhiyun': 'Nantong',
        'Dalian Pro': 'Dalian',
        'Dalian Yingbo': 'Dalian',
        'Yunnan Yukun': 'Kunming',
        'Wuhan Three Towns': 'Wuhan'
    },
    
    # Danish Superliga
    'den.1': {
        'AGF': 'Aarhus',
        'AaB': 'Aalborg',
        'Brøndby': 'Brøndby',
        'Brøndby IF': 'Brøndby',
        'Copenhagen': 'Copenhagen',
        'F.C. København': 'Copenhagen',
        'FC Midtjylland': 'Herning',
        'FC Nordsjælland': 'Farum',
        'Hvidovre': 'Hvidovre',
        'Lyngby': 'Lyngby',
        'Lyngby Boldklub': 'Lyngby',
        'OB': 'Odense',
        'Randers': 'Randers',
        'Randers FC': 'Randers',
        'Silkeborg': 'Silkeborg',
        'Silkeborg IF': 'Silkeborg',
        'Sønderjyske': 'Haderslev',
        'Sønderjyske Fodbold': 'Haderslev',
        'Vejle': 'Vejle',
        'Vejle Boldklub': 'Vejle',
        'Viborg': 'Viborg',
        'Viborg FF': 'Viborg'
    },
    
    # Egyptian Premier League
    'egy.1': {
        "Al Ahly": "Cairo",
        "Al Masry": "Port Said",
        "Al Mokawloon Al Arab": "Cairo",
        "Aswan SC": "Aswan",
        "Ceramica Cleopatra": "Cairo",
        "El Daklyeh": "Cairo",
        "El Gouna": "El Gouna",
        "ENPPI": "Cairo",
        "Future FC": "Cairo",
        "Ghazl El Mahalla": "El Mahalla El Kubra",
        "Ismaily": "Ismailia",
        "Ittihad Alexandria": "Alexandria",
        "National Bank of Egypt": "Cairo",
        "Pharco": "Alexandria",
        "Pyramids": "Cairo",
        "Smouha": "Alexandria",
        "Tala'ea El Gaish": "Cairo",
        "Zamalek": "Cairo"
    },
    
    # English Premier League
    'eng.1': {
        'Arsenal': 'London',
        'Aston Villa': 'Birmingham',
        'Brighton & Hove Albion': 'Brighton',
        'Chelsea': 'London',
        'Crystal Palace': 'London',
        'Everton': 'Liverpool',
        'Fulham': 'London',
        'Ipswich Town': 'Ipswich',
        'Leicester City': 'Leicester',
        'Liverpool': 'Liverpool',
        'Luton Town': 'Luton',
        'Manchester City': 'Manchester',
        'Manchester United': 'Manchester',
        'Newcastle United': 'Newcastle upon Tyne',
        'Nottingham Forest': 'Nottingham',
        'Sheffield United': 'Sheffield',
        'Southampton': 'Southampton',
        'Tottenham Hotspur': 'London',
        'West Ham United': 'London',
        'Wolverhampton Wanderers': 'Wolverhampton',
        "AFC Bournemouth": "Bournemouth",
        "Brentford": "London",
    },
    
    # English Championship
    'eng.2': {
        'Burnley': 'Burnley',
        'Derby County': 'Derby',
        'Leeds United': 'Leeds',
        'Luton Town': 'Luton',
        'Plymouth Argyle': 'Plymouth',
        'Sheffield United': 'Sheffield',
        'Sheffield Wednesday': 'Sheffield',
        'Norwich City': 'Norwich',
        'Middlesbrough': 'Middlesbrough',
        'Hull City': 'Hull',
        'Cardiff City': 'Cardiff',
        'Swansea City': 'Swansea',
        'Bristol City': 'Bristol',
        'Birmingham City': 'Birmingham',
        'Blackburn Rovers': 'Blackburn',
        'Watford': 'Watford',
        'Stoke City': 'Stoke-on-Trent',
        'Millwall': 'London',
        'Queens Park Rangers': 'London',
        'Coventry City': 'Coventry',
        'Sunderland': 'Sunderland',
        'Preston North End': 'Preston',
        'Reading': 'Reading',
        'Huddersfield Town': 'Huddersfield',
        'Rotherham United': 'Rotherham',
        "Portsmouth": "Portsmouth",
        "Oxford United": "Oxford",
        "West Bromwich Albion": "West Bromwich",
    },
    
    # English League One
    'eng.3': {
        "AFC Wimbledon": "London",
        "Barnsley": "Barnsley",
        "Birmingham City": "Birmingham",
        "Blackpool": "Blackpool",
        "Bolton Wanderers": "Bolton",
        "Bristol Rovers": "Bristol",
        "Burton Albion": "Burton upon Trent",
        "Cambridge United": "Cambridge",
        "Carlisle United": "Carlisle",
        "Charlton Athletic": "London",
        "Cheltenham Town": "Cheltenham",
        "Crawley Town": "Crawley",
        "Derby County": "Derby",
        "Exeter City": "Exeter",
        "Fleetwood Town": "Fleetwood",
        "Huddersfield Town": "Huddersfield",
        "Leyton Orient": "London",
        "Lincoln City": "Lincoln",
        "Mansfield Town": "Mansfield",
        "Northampton Town": "Northampton",
        "Oxford United": "Oxford",
        "Peterborough United": "Peterborough",
        "Port Vale": "Stoke-on-Trent",
        "Reading": "Reading",
        "Rotherham United": "Rotherham",
        "Shrewsbury Town": "Shrewsbury",
        "Stevenage": "Stevenage",
        "Stockport County": "Stockport",
        "Wigan Athletic": "Wigan",
        "Wycombe Wanderers": "High Wycombe",
        "Wrexham": "Wrexham",
    },
    
    # English League Two
    'eng.4': {
        "Accrington Stanley": "Accrington",
        "AFC Wimbledon": "London",
        "Barrow": "Barrow-in-Furness",
        "Bradford City": "Bradford",
        "Bromley": "London",
        "Carlisle United": "Carlisle",
        "Cheltenham Town": "Cheltenham",
        "Chesterfield": "Chesterfield",
        "Colchester United": "Colchester",
        "Crawley Town": "Crawley",
        "Crewe Alexandra": "Crewe",
        "Doncaster Rovers": "Doncaster",
        "Fleetwood Town": "Fleetwood",
        "Forest Green Rovers": "Nailsworth",
        "Gillingham": "Gillingham",
        "Grimsby Town": "Grimsby",
        "Harrogate Town": "Harrogate",
        "Leyton Orient": "London",
        "Mansfield Town": "Mansfield",
        "Milton Keynes Dons": "Milton Keynes",
        "Morecambe": "Morecambe",
        "Newport County": "Newport",
        "Notts County": "Nottingham",
        "Port Vale": "Stoke-on-Trent",
        "Rochdale": "Rochdale",
        "Salford City": "Salford",
        "Stockport County": "Stockport",
        "Sutton United": "London",
        "Swindon Town": "Swindon",
        "Tranmere Rovers": "Birkenhead",
        "Walsall": "Walsall",
    },
    
    # English National League
    'eng.5': {
        'Chesterfield': 'Chesterfield',
        'Barnet': 'London',
        'Bromley': 'London',
        'Gateshead': 'Gateshead',
        'Aldershot Town': 'Aldershot',
        'Altrincham': 'Altrincham',
        'Dagenham & Redbridge': 'London',
        'Dorking Wanderers': 'Dorking',
        'Eastleigh': 'Eastleigh',
        'Ebbsfleet United': 'Northfleet',
        'FC Halifax Town': 'Halifax',
        'Forest Green Rovers': 'Nailsworth',
        'Hartlepool United': 'Hartlepool',
        'Kidderminster Harriers': 'Kidderminster',
        'Maidenhead United': 'Maidenhead',
        'Oldham Athletic': 'Oldham',
        'Oxford City': 'Oxford',
        'Rochdale': 'Rochdale',
        'Solihull Moors': 'Solihull',
        'Southend United': 'Southend-on-Sea',
        'Sutton United': 'London',
        'Wealdstone': 'London',
        'Woking': 'Woking',
        'York City': 'York',
        'AFC Fylde': 'Wesham',
        'Boston United': 'Boston',
        'Braintree Town': 'Braintree',
        'Tamworth': 'Tamworth',
        'Yeovil Town': 'Yeovil'
    },
    
    # Spanish La Liga
    'esp.1': {
        'Barcelona': 'Barcelona',
        'Real Madrid': 'Madrid',
        'Atlético Madrid': 'Madrid',
        'Athletic Club': 'Bilbao',
        'Real Sociedad': 'San Sebastian',
        'Real Betis': 'Seville',
        'Sevilla': 'Seville',
        'Valencia': 'Valencia',
        'Villarreal': 'Villarreal',
        'Celta Vigo': 'Vigo',
        'Rayo Vallecano': 'Madrid',
        'Osasuna': 'Pamplona',
        'Mallorca': 'Palma',
        'Getafe': 'Getafe',
        'Girona': 'Girona',
        'Las Palmas': 'Las Palmas',
        'Alavés': 'Vitoria-Gasteiz',
        'Granada': 'Granada',
        'Cádiz': 'Cádiz',
        'Almería': 'Almería',
        'Espanyol': 'Barcelona',
        'Leganés': 'Leganés',
        'Real Valladolid': 'Valladolid'
    },
    
    # Spanish Segunda División
    'esp.2': {
        'Albacete': 'Albacete',
        'Alcorcón': 'Alcorcón',
        'Amorebieta': 'Amorebieta-Etxano',
        'Andorra': 'Andorra la Vella',
        'Burgos': 'Burgos',
        'Burgos CF': 'Burgos',
        'Cartagena': 'Cartagena',
        'Deportivo La Coruña': 'A Coruña',
        'Eldense': 'Elda',
        'Elche': 'Elche',
        'Eibar': 'Eibar',
        'FC Cartagena': 'Cartagena',
        'Granada': 'Granada',
        'Levante': 'Valencia',
        'Mirandés': 'Miranda de Ebro',
        'Málaga': 'Málaga',
        'Racing Santander': 'Santander',
        'Real Valladolid': 'Valladolid',
        'Real Zaragoza': 'Zaragoza',
        'Sporting Gijón': 'Gijón',
        'Tenerife': 'Santa Cruz de Tenerife',
        'Villarreal B': 'Villarreal',
        'Almería': 'Almería',
        'Castellón': 'Castellón de la Plana',
        'Cádiz': 'Cádiz',
        'Córdoba': 'Córdoba',
        'Huesca': 'Huesca',
        'Racing Ferrol': 'Ferrol',
        'Real Oviedo': 'Oviedo'
    },
    
    # French Ligue 1
    'fra.1': {
        'Paris Saint-Germain': 'Paris',
        'Marseille': 'Marseille',
        'AS Monaco': 'Monaco',
        'Lyon': 'Lyon',
        'Lille': 'Lille',
        'Rennes': 'Rennes',
        'Nice': 'Nice',
        'Lens': 'Lens',
        'Strasbourg': 'Strasbourg',
        'Nantes': 'Nantes',
        'Montpellier': 'Montpellier',
        'Brest': 'Brest',
        'Troyes': 'Troyes',
        'Lorient': 'Lorient',
        'Clermont Foot': 'Clermont-Ferrand',
        'Toulouse': 'Toulouse',
        'Reims': 'Reims',
        'Auxerre': 'Auxerre',
        'AJ Auxerre': 'Auxerre',
        'Angers': 'Angers',
        'Le Havre AC': 'Le Havre',
        'Saint-Etienne': 'Saint-Étienne',
        'Stade Rennais': 'Rennes',
        'Stade de Reims': 'Reims'
    },
    
    # French Ligue 2
    'fra.2': {
        "AC Ajaccio": "Ajaccio",
        "AJ Auxerre": "Auxerre",
        "Amiens SC": "Amiens",
        "AS Saint-Étienne": "Saint-Étienne",
        "Angers SCO": "Angers",
        "Bordeaux": "Bordeaux",
        "Caen": "Caen",
        "Concarneau": "Concarneau",
        "Dunkerque": "Dunkirk",
        "EA Guingamp": "Guingamp",
        "Grenoble": "Grenoble",
        "Laval": "Laval",
        "Paris FC": "Paris",
        "Pau FC": "Pau",
        "Quevilly Rouen": "Le Petit-Quevilly",
        "Rodez": "Rodez",
        "SC Bastia": "Bastia",
        "Troyes": "Troyes",
        "Valenciennes": "Valenciennes",
        "Annecy": "Annecy",
        "Bastia": "Bastia",
        "Clermont Foot": "Clermont-Ferrand",
        "Guingamp": "Guingamp",
        "Lorient": "Lorient",
        "Martigues": "Martigues",
        "Metz": "Metz",
        "Pau": "Pau",
        "Red Star FC 93": "Saint-Ouen",
        "Rodez Aveyron": "Rodez",
        "SC Amiens": "Amiens",
        "Stade Laval": "Laval"
    },
    
    # German Bundesliga
    'ger.1': {
        'Bayern Munich': 'Munich',
        'Borussia Dortmund': 'Dortmund',
        'RB Leipzig': 'Leipzig',
        'Bayer Leverkusen': 'Leverkusen',
        'Eintracht Frankfurt': 'Frankfurt',
        'VfL Wolfsburg': 'Wolfsburg',
        'Borussia Mönchengladbach': 'Mönchengladbach',
        'SC Freiburg': 'Freiburg',
        'FC Köln': 'Cologne',
        'FSV Mainz 05': 'Mainz',
        'Union Berlin': 'Berlin',
        'Hertha BSC': 'Berlin',
        'TSG Hoffenheim': 'Sinsheim',
        'VfB Stuttgart': 'Stuttgart',
        'Werder Bremen': 'Bremen',
        'FC Augsburg': 'Augsburg',
        'VfL Bochum': 'Bochum',
        'Schalke 04': 'Gelsenkirchen',
        'St. Pauli': 'Hamburg',
        'Holstein Kiel': 'Kiel',
        'FC Heidenheim': 'Heidenheim',
        '1. FC Heidenheim 1846': 'Heidenheim',
        '1. FC Union Berlin': 'Berlin',
        'Borussia Monchengladbach': 'Mönchengladbach',
        'Mainz': 'Mainz'
    },
    
    # German 2. Bundesliga
    'ger.2': {
        "Kaiserslautern": "Kaiserslautern",
        "FC Kaiserslautern": "Kaiserslautern",
        "Schalke 04": "Gelsenkirchen",
        "FC Schalke 04": "Gelsenkirchen",
        "FC Magdeburg": "Magdeburg",
        "1. FC Magdeburg": "Magdeburg",
        "FC Nürnberg": "Nuremberg",
        "1. FC Nürnberg": "Nuremberg",
        "FC Köln": "Cologne",
        "FC Cologne": "Cologne",
        "Eintracht Braunschweig": "Braunschweig",
        "TSV Eintracht Braunschweig": "Braunschweig",
        "St. Pauli": "Hamburg",
        "Fortuna Düsseldorf": "Düsseldorf",
        "Greuther Fürth": "Fürth",
        "SpVgg Greuther Furth": "Fürth",
        "Hamburger SV": "Hamburg",
        "Hamburg SV": "Hamburg",
        "Hannover 96": "Hanover",
        "Hertha BSC": "Berlin",
        "Hertha Berlin": "Berlin",
        "Holstein Kiel": "Kiel",
        "Karlsruher SC": "Karlsruhe",
        "SC Paderborn 07": "Paderborn",
        "SV Elversberg": "Spiesen-Elversberg",
        "SV 07 Elversberg": "Spiesen-Elversberg",
        "VfL Osnabrück": "Osnabrück",
        "Wehen Wiesbaden": "Wiesbaden",
        "SSV Jahn Regensburg": "Regensburg",
        "SSV Ulm 1846": "Ulm",
        "SV Darmstadt 98": "Darmstadt",
        "Preußen Münster": "Münster"
    },
    
    # Greek Super League
    'gre.1': {
        'Olympiacos': 'Piraeus',
        'Panathinaikos': 'Athens',
        'AEK Athens': 'Athens',
        'PAOK': 'Thessaloniki',
        'PAOK Salonika': 'Thessaloniki',
        'Aris': 'Thessaloniki',
        'Asteras Tripoli': 'Tripoli',
        'Athens Kallithea': 'Athens',
        'Levadiakos': 'Livadeia',
        'OFI': 'Heraklion',
        'OFI Crete': 'Heraklion',
        'Panetolikos': 'Agrinio',
        'Panserraikos': 'Serres',
        'Panserraikos FC': 'Serres',
        'Volos': 'Volos',
        'Volos NFC': 'Volos',
        'Panathinaikos': 'Athens',
        'Asteras Tripolis': 'Tripoli',
        'Atromitos': 'Peristeri',
        'Ionikos': 'Piraeus',
        'Lamia': 'Lamia',
        'PAS Giannina': 'Ioannina'
    },
    
    # Italian Serie A
    'ita.1': {
        'AC Milan': 'Milan',
        'Inter Milan': 'Milan',
        'Juventus': 'Turin',
        'Roma': 'Rome',
        'AS Roma': 'Rome',
        'Lazio': 'Rome',
        'Napoli': 'Naples',
        'Atalanta': 'Bergamo',
        'Fiorentina': 'Florence',
        'Bologna': 'Bologna',
        'Torino': 'Turin',
        'Genoa': 'Genoa',
        'Monza': 'Monza',
        'Lecce': 'Lecce',
        'Udinese': 'Udine',
        'Cagliari': 'Cagliari',
        'Verona': 'Verona',
        'Hellas Verona': 'Verona',
        'Frosinone': 'Frosinone',
        'Empoli': 'Empoli',
        'Sassuolo': 'Sassuolo',
        'Salernitana': 'Salerno',
        'Como': 'Como',
        'Internazionale': 'Milan',
        'Parma': 'Parma',
        'Venezia': 'Venice'
    },
    
    # Italian Serie B
    'ita.2': {
        'Parma': 'Parma',
        'Cremonese': 'Cremona',
        'Venezia': 'Venice',
        'Catanzaro': 'Catanzaro',
        'Palermo': 'Palermo',
        'Bari': 'Bari',
        'Cittadella': 'Cittadella',
        'Reggiana': 'Reggio Emilia',
        'Südtirol': 'Bolzano',
        'Modena': 'Modena',
        'Ternana': 'Terni',
        'Brescia': 'Brescia',
        'Ascoli': 'Ascoli Piceno',
        'Spezia': 'La Spezia',
        'Carrarese': 'Carrara',
        'Cesena': 'Cesena',
        'Frosinone': 'Frosinone',
        'Juve Stabia': 'Castellammare di Stabia',
        'Mantova': 'Mantua',
        'Salernitana': 'Salerno',
        'Sassuolo': 'Sassuolo',
        'Suditrol': 'Bolzano',
        'Cosenza': 'Cosenza',
        'Pisa': 'Pisa',
        'Sampdoria': 'Genoa'
    },
    
    # Japanese J1 League
    'jpn.1': {
        'Kashima Antlers': 'Kashima',
        'Urawa Red Diamonds': 'Saitama',
        'Sanfrecce Hiroshima': 'Hiroshima',
        'Kawasaki Frontale': 'Kawasaki',
        'Cerezo Osaka': 'Osaka',
        'Gamba Osaka': 'Osaka',
        'Vissel Kobe': 'Kobe',
        'Nagoya Grampus': 'Nagoya',
        'FC Tokyo': 'Tokyo',
        'Yokohama F. Marinos': 'Yokohama',
        'Shonan Bellmare': 'Hiratsuka',
        'Consadole Sapporo': 'Sapporo',
        'Albirex Niigata': 'Niigata',
        'Fagiano Okayama': 'Okayama',
        'Machida Zelvia': 'Machida',
        'Tokyo Verdy 1969': 'Tokyo',
        'Yokohama FC': 'Yokohama',
        'Avispa Fukuoka': 'Fukuoka',
        'Sagan Tosu': 'Tosu',
        'Kyoto Sanga': 'Kyoto',
        'Kashiwa Reysol': 'Kashiwa',
        'Shimizu S-Pulse': 'Shizuoka'
    },
    
    # Dutch Eredivisie
    'ned.1': {
        'Ajax': 'Amsterdam',
        'Ajax Amsterdam': 'Amsterdam',
        'PSV': 'Eindhoven',
        'PSV Eindhoven': 'Eindhoven',
        'Feyenoord': 'Rotterdam',
        'Feyenoord Rotterdam': 'Rotterdam',
        'AZ': 'Alkmaar',
        'AZ Alkmaar': 'Alkmaar',
        'FC Twente': 'Enschede',
        'FC Utrecht': 'Utrecht',
        'Sparta Rotterdam': 'Rotterdam',
        'Heerenveen': 'Heerenveen',
        'NEC': 'Nijmegen',
        'NEC Nijmegen': 'Nijmegen',
        'RKC Waalwijk': 'Waalwijk',
        'Fortuna Sittard': 'Sittard',
        'Go Ahead Eagles': 'Deventer',
        'Excelsior': 'Rotterdam',
        'Almere City': 'Almere',
        'Heracles Almelo': 'Almelo',
        'NAC Breda': 'Breda',
        'PEC Zwolle': 'Zwolle',
        'Willem II': 'Tilburg',
        'FC Groningen': 'Groningen'
    },
    
    # Portuguese Primeira Liga
    'por.1': {
        'Benfica': 'Lisbon',
        'Porto': 'Porto',
        'FC Porto': 'Porto',
        'Sporting CP': 'Lisbon',
        'Braga': 'Braga',
        'Vitória SC': 'Guimarães',
        'Guimaraes': 'Guimarães',
        'Moreirense': 'Moreira de Cónegos',
        'Famalicão': 'Vila Nova de Famalicão',
        'FC Famalicao': 'Vila Nova de Famalicão',
        'Boavista': 'Porto',
        'Casa Pia': 'Lisbon',
        'Estoril': 'Estoril',
        'Estrela': 'Amadora',
        'Farense': 'Faro',
        'SC Farense': 'Faro',
        'Gil Vicente': 'Barcelos',
        'Nacional': 'Funchal',
        'C.D. Nacional': 'Funchal',
        'Portimonense': 'Portimão',
        'Rio Ave': 'Vila do Conde',
        'Santa Clara': 'Ponta Delgada',
        'Vizela': 'Vizela',
        'AVS': 'Vila das Aves',
        'Arouca': 'Arouca'
    },
    
    # Major League Soccer
    'usa.1': {
        'Atlanta United FC': 'Atlanta',
        'Austin FC': 'Austin',
        'CF Montréal': 'Montreal',
        'Charlotte FC': 'Charlotte',
        'Chicago Fire FC': 'Chicago',
        'Colorado Rapids': 'Commerce City',
        'Columbus Crew': 'Columbus',
        'D.C. United': 'Washington',
        'FC Cincinnati': 'Cincinnati',
        'FC Dallas': 'Frisco',
        'Houston Dynamo FC': 'Houston',
        'Inter Miami CF': 'Fort Lauderdale',
        'LA Galaxy': 'Carson',
        'Los Angeles FC': 'Los Angeles',
        'Minnesota United FC': 'Saint Paul',
        'Montreal Impact': 'Montreal',
        'Nashville SC': 'Nashville',
        'New England Revolution': 'Foxborough',
        'New York City FC': 'New York City',
        'New York Red Bulls': 'Harrison',
        'Orlando City SC': 'Orlando',
        'Philadelphia Union': 'Chester',
        'Portland Timbers': 'Portland',
        'Real Salt Lake': 'Sandy',
        'San Jose Earthquakes': 'San Jose',
        'Seattle Sounders FC': 'Seattle',
        'Sporting Kansas City': 'Kansas City',
        'St. Louis City SC': 'St. Louis',
        'Toronto FC': 'Toronto',
        'Vancouver Whitecaps FC': 'Vancouver'
    },
    
    # South African Premier Soccer League
    'rsa.1': {
        "Amazulu": "Durban",
        "Cape Town City": "Cape Town",
        "Chippa United": "Port Elizabeth",
        "Golden Arrows": "Durban",
        "Kaizer Chiefs": "Johannesburg",
        "Lamontville Golden Arrows": "Durban",
        "Magesi FC": "Polokwane",
        "Mamelodi Sundowns": "Pretoria",
        "Maritzburg United": "Pietermaritzburg",
        "Marumo Gallants": "Polokwane",
        "Moroka Swallows": "Johannesburg",
        "Orlando Pirates": "Johannesburg",
        "Polokwane City": "Polokwane",
        "Richards Bay": "Richards Bay",
        "Royal AM": "Durban",
        "Sekhukhune United": "Polokwane",
        "Stellenbosch": "Stellenbosch",
        "SuperSport United": "Pretoria",
        "TS Galaxy": "Mpumalanga",
        "University of Pretoria": "Pretoria"
    },
    
    # South African First Division
    'rsa.2': {
        'Black Leopards': 'Thohoyandou',
        'Cape Town Spurs': 'Cape Town',
        'Casric Stars': 'Mpumalanga',
        'Hungry Lions': 'Kimberley',
        'JDR Stars': 'Pretoria',
        'La Masia': 'Pretoria',
        'Milford FC': 'Durban',
        'MM Platinum': 'Rustenburg',
        'NB La Masia': 'Pretoria',
        'Pretoria Callies': 'Pretoria',
        'Venda Football Academy': 'Thohoyandou',
        'Upington City': 'Upington',
        'Baroka FC': 'Polokwane',
        'Cape Town Spurs FC': 'Cape Town',
        'Durban City': 'Durban',
        'Highbury': 'Pretoria',
        'Kruger United': 'Nelspruit',
        'Leruma United': 'Pretoria',
        'Orbit College': 'Rustenburg',
        'Pretoria University': 'Pretoria',
        'Venda Football Acadamy': 'Thohoyandou'
    },
    
    # Moroccan Botola Pro
    # ... existing code ...
} 