#!/usr/bin/env python3
import argparse
import datetime
import sys

def food_of_day_interval(month=None, day=None, interval=1):
    now = datetime.datetime.now()
    year = now.year
    if not month:
        month = now.month
    if not day:
        day = now.day
    for counter in range(interval):
        date = datetime.datetime(year=year,month=month, day=day) + datetime.timedelta(days=counter)
        month0 = date.month
        day0 = date.day
        print(f"{date.strftime('%a')} {month0}/{day0} {food_of_day(month0, day0)}")

def food_of_day(month=None, day=None):
    if month is None or day is None:
        now = datetime.datetime.now()
        month = now.month
        day = now.day
    return {
        (1,1):   "Bloody Mary Day",
        (1,2):   "Cream Puff Day",
        (1,3):   "Chocolate Covered Cherry Day",
        (1,4):   "Spaghetti Day",
        (1,5):   "Whipped Cream Day",
        (1,6):   "Shortbread Day",
        (1,7):   "Tempura Day",
        (1,8):   "English Toffee Day",
        (1,9):   "Apricot Day",
        (1,10):  "Bittersweet Chocolate Day",
        (1,11):  "Hot Toddy Day",
        (1,12):  "Marzipan Day",
        (1,13):  "Peach Melba Day",
        (1,14):  "Hot Pastrami Sandwich Day",
        (1,15):  "Fresh Squeezed Juice Day",
        (1,16):  "Fig Newton Day",
        (1,17):  "Hot Buttered Rum Day",
        (1,18):  "Peking Duck Day",
        (1,19):  "Popcorn Day",
        (1,20):  "Buttercrunch Day",
        (1,21):  "Granola Bar Day",
        (1,22):  "Blonde Brownie Day",
        (1,23):  "Rhubarb Pie Day",
        (1,24):  "Peanut Butter Day",
        (1,25):  "Irish Coffee Day",
        (1,26):  "Peanut Brittle Day",
        (1,27):  "Chocolate Cake Day",
        (1,28):  "Blueberry Pancake Day",
        (1,29):  "Corn Chip Day",
        (1,30):  "Croissant Day",
        (1,31):  "Brandy Alexander Day",
        (2,1):   "Baked Alaska Day",
        (2,2):   "Heavenly Hash Day",
        (2,3):   "Carrot Cake Day",
        (2,4):   "Homemade Soup Day",
        (2,5):   "Chocolate Fondue Day",
        (2,6):   "Frozen Yogurt Day",
        (2,7):   "Fettucine Alfredo Day",
        (2,8):   "Molasses Bar Day",
        (2,9):   "Bagels and Lox Day",
        (2,10):  "Cream Cheese Brownie Day",
        (2,11):  "Peppermint Patty Day",
        (2,12):  "Plum Pudding Day",
        (2,13):  "Tortini Day",
        (2,14):  "Cream Filled Chocolates Day",
        (2,15):  "InterGumdrop Day",
        (2,16):  "Almond Day",
        (2,17):  "Cafe Au Lait Day",
        (2,18):  "Crab Stuffed Flounder Day",
        (2,19):  "Chocolate Mint Day",
        (2,20):  "Cherry Pie Day",
        (2,21):  "Sticky Bun Day",
        (2,22):  "Margarita Day",
        (2,23):  "Banana Bread Day",
        (2,24):  "Tortilla Chip Day",
        (2,25):  "Chocolate Covered Peanuts Day",
        (2,26):  "Pistachio Day",
        (2,27):  "Kahlua Day",
        (2,28):  "Chocolate Souffle Day",
        (2,29):  "Surf and Turf Day",
        (3,1):   "Peanut Butter Lover’s Day",
        (3,2):   "Banana Cream Pie Day",
        (3,3):   "Mulled Wine Day",
        (3,4):   "Pound Cake Day",
        (3,5):   "Cheese Doodle Day",
        (3,6):   "Frozen Food Day",
        (3,7):   "Crown Roast of Pork Day",
        (3,8):   "Peanut Cluster Day",
        (3,9):   "Crabmeat Day",
        (3,10):  "Blueberry Popover Day",
        (3,11):  "Oatmeal-Nut Waffle Day",
        (3,12):  "Baked Scallops Day",
        (3,13):  "Coconut Torte Day",
        (3,14):  "Potato Chip Day",
        (3,15):  "Pears Helene Day",
        (3,16):  "Artichoke Hearts Day",
        (3,17):  "Green Beer Day",
        (3,18):  "Lacy Oatmeal Cookie Day",
        (3,19):  "Chocolate Carmel Day",
        (3,20):  "Ravioli Day",
        (3,21):  "French Bread Day",
        (3,22):  "Bavarian Crepes Day",
        (3,23):  "Chip and Dip Day",
        (3,24):  "Chocolate Covered Raisins Day",
        (3,25):  "Lobster Newburg Day",
        (3,26):  "Nougat Day",
        (3,27):  "Spanish Paella Day",
        (3,28):  "Black Forest Cake Day",
        (3,29):  "Lemon Chiffon Cake Day",
        (3,30):  "Turkey Neck Soup Day",
        (3,31):  "Clams on the Half Shell Day",
        (4,1):   "Sourdough Bread Day",
        (4,2):   "Peanut Butter & Jelly Day",
        (4,3):   "Chocolate Moose Day",
        (4,4):   "Chocolate Milk Powder Day",
        (4,5):   "Caramel Day",
        (4,6):   "Fresh Tomato Day",
        (4,7):   "Coffee Cake Day",
        (4,8):   "Empanada Day",
        (4,9):   "Chinese Almond Cookie Day",
        (4,10):  "Cinnamon Crescent Day",
        (4,11):  "Cheese Fondue Day",
        (4,12):  "Grilled Cheese Sandwich Day",
        (4,13):  "Peach Cobbler Day",
        (4,14):  "Pecan Day",
        (4,15):  "Glazed Spiral Ham Day",
        (4,16):  "Eggs Benedict Day",
        (4,17):  "Cheese Ball Day",
        (4,18):  "Animal Cracker Day",
        (4,19):  "Garlic Day Day",
        (4,20):  "Pineapple Upside-Down Cake Day",
        (4,21):  "Chocolate-Covered Cashew Truffle Day",
        (4,22):  "Jelly Bean Day",
        (4,23):  "Picnic Day",
        (4,24):  "Pigs-in-a-Blanket Day",
        (4,25):  "Zucchini Bread Day",
        (4,26):  "Pretzel Day",
        (4,27):  "Prime Rib Day",
        (4,28):  "Blueberry Pie Day",
        (4,29):  "Shrimp Scampi Day",
        (4,30):  "Oatmeal Cookie Day",
        (5,1):   "Chocolate Parfait Day",
        (5,2):   "Truffles Day",
        (5,3):   "Raspberry Tart Day",
        (5,4):   "Candied Orange Peel Day",
        (5,5):   "Chocolate Custard Day",
        (5,6):   "Crepes Suzette Day",
        (5,7):   "Roast Leg of Lamb Day",
        (5,8):   "Coconut Cream Pie Day",
        (5,9):   "Butterscotch Brownie Day",
        (5,10):  "Shrimp Day",
        (5,11):  "Mocha Torte Day",
        (5,11):  "Eat What You Want Day",
        (5,12):  "Nutty Fudge Day",
        (5,13):  "Fruit Cocktail Day",
        (5,14):  "Buttermilk Biscuit Day",
        (5,15):  "Chocolate Chip Day",
        (5,16):  "Coquilles St. Jacques Day",
        (5,17):  "Cherry Cobbler Day",
        (5,18):  "Cheese Soufflé Day",
        (5,19):  "Devil’s Food Cake Day",
        (5,20):  "Quiche Lorraine Day",
        (5,21):  "Strawberries & Cream Day",
        (5,22):  "Vanilla Pudding Day",
        (5,23):  "Taffy Day",
        (5,24):  "Escargot Day",
        (5,25):  "Wine Day",
        (5,26):  "Cherry Dessert Day",
        (5,27):  "Grape Popsicle Day",
        (5,28):  "Brisket Day",
        (5,29):  "Coq Au Vin Day",
        (5,30):  "Macaroon Day",
        (6,1):   "Hazelnut Cake Day",
        (6,2):   "Rocky Road Day",
        (6,3):   "Chocolate Macaroon Day",
        (6,4):   "Frozen Yogurt Day",
        (6,5):   "Gingerbread Day",
        (6,6):   "Applesauce Cake Day",
        (6,7):   "Chocolate Ice Cream Day",
        (6,8):   "Jelly-filled Doughnut Day",
        (6,9):   "Strawberry Rhubarb Pie Day",
        (6,10):  "Black Cow Day",
        (6,11):  "German Chocolate Day",
        (6,12):  "Peanut Butter Cookie Day",
        (6,13):  "Lobster Day",
        (6,14):  "Strawberry Shortcake Day",
        (6,15):  "Kitchen Klutzes of America Day",
        (6,16):  "Fudge Day",
        (6,17):  "Apple Streudel Day",
        (6,18):  "Cherry Tart Day",
        (6,19):  "Martini Day",
        (6,20):  "Vanilla Milkshake Day",
        (6,21):  "Peaches & Cream Day",
        (6,22):  "Chocolate Eclair Day",
        (6,23):  "Pecan Sandy Day",
        (6,24):  "Creamy Pralines Day",
        (6,25):  "Strawberry Parfait Day",
        (6,26):  "Chocolate Pudding Day",
        (6,27):  "Orange Blossom Day",
        (6,28):  "Tapioca Day",
        (6,29):  "Almond Butter Crunch Day",
        (6,30):  "Mai Tai Day",
        (7,1):   "Creative Ice Cream Flavor Day",
        (7,2):   "Anisette Day",
        (7,3):   "Eat Beans Day",
        (7,4):   "Barbecued Spareribs Day",
        (7,5):   "Graham Cracker Day",
        (7,6):   "Fried Chicken Day",
        (7,7):   "Strawberry Sundae Day",
        (7,8):   "Milk Chocolate with Almonds Day",
        (7,9):   "Sugar Cookie Day",
        (7,10):  "Pina Colada Day",
        (7,11):  "Blueberry Muffin Day",
        (7,12):  "Eat Your Jello Day",
        (7,13):  "French Fries Day",
        (7,14):  "Grand Marnier Day",
        (7,15):  "Tapioca Pudding Day",
        (7,16):  "Fresh Spinach Day",
        (7,17):  "Peach Ice Cream Day",
        (7,18):  "Caviar Day",
        (7,19):  "Daiquiri Day",
        (7,20):  "Lollipop Day",
        (7,21):  "Creme Brulee Day",
        (7,22):  "PMaple Syrup Day",
        (7,23):  "Hot Dog Day",
        (7,24):  "Tequila Day",
        (7,25):  "Hot Fudge Sundae Day",
        (7,26):  "Coffee Milkshake Day",
        (7,27):  "Scotch Day",
        (7,28):  "Milk Chocolate Day",
        (7,29):  "Lasagna Day",
        (7,30):  "Cheesecake Day",
        (7,31):  "Jump for Jelly Beans Day",
        (8,1):   "Raspberry Cream Pie Day",
        (8,2):   "Ice Cream Sandwich Day",
        (8,3):   "Watermelon Day",
        (8,4):   "Chocolate Chip Day",
        (8,5):   "Chile Pepper Day",
        (8,6):   "Root Beer Float Day",
        (8,7):   "Raspberries & Cream Day",
        (8,8):   "Frozen Custard Day",
        (8,9):   "Rice Pudding Day",
        (8,10):  "S’mores Day",
        (8,11):  "Raspberry Bombe Day",
        (8,12):  "Toasted Almond Bar Day",
        (8,13):  "Filet Mignon Day",
        (8,14):  "Creamsicle Day",
        (8,15):  "Lemon Meringue Pie Day",
        (8,16):  "Rum Day",
        (8,17):  "Vanilla Custard Day",
        (8,18):  "Ice Cream Pie Day",
        (8,19):  "Soft Ice Cream Day",
        (8,20):  "Lemonade Day",
        (8,21):  "Spumoni Day",
        (8,22):  "Pecan Torte Day",
        (8,23):  "Spongecake Day",
        (8,24):  "Peach Pie Day",
        (8,25):  "Waffle Day",
        (8,26):  "Cherry Popsicle Day",
        (8,27):  "Banana Lover’s Day",
        (8,28):  "Cherry Turnover Day",
        (8,29):  "More Herbs Less Salt Day",
        (8,29):  "Lemon Juice Day",
        (8,30):  "Marshmallow Toasting Day",
        (8,31):  "Trail Mix Day",
        (9,1):   "Cherry Popover Day",
        (9,2):   "Blueberry Popsicle Day",
        (9,3):   "Welsh Rabbit Day",
        (9,4):   "Macadamia Nut Day",
        (9,5):   "Cheese Pizza Day",
        (9,6):   "Coffee Ice Cream Day",
        (9,7):   "Napoleon Day",
        (9,8):   "Date-Nut Bread Day",
        (9,9):   "Steak au Poivre Day",
        (9,10):  "Oatmeal Day",
        (9,11):  "Hot Cross Bun Day",
        (9,12):  "Chocolate Milkshake Day",
        (9,13):  "Peanut Day",
        (9,14):  "Cream-Filled Donut Day",
        (9,15):  "Creme de Menthe Day",
        (9,16):  "Homemade Bread Day",
        (9,17):  "Apple Dumpling Day",
        (9,18):  "Eat A Cranberry Day",
        (9,19):  "Butterscotch Pudding Day",
        (9,20):  "Rum Punch Day",
        (9,21):  "Pecan Cookie Day",
        (9,22):  "White Chocolate Day",
        (9,23):  "Chocolate Day",
        (9,24):  "Cherries Jubilee Day",
        (9,25):  "Crab Newberg Day",
        (9,26):  "Pancake Day",
        (9,27):  "Chocolate Milk Day",
        (9,28):  "Strawberry Cream Pie Day",
        (9,29):  "Mocha Day",
        (9,30):  "Mulled Cider Day",
        (10,1):  "World Vegetarian Day",
        (10,2):  "French Fried Scallops Day",
        (10,3):  "Caramel Custard Day",
        (10,4):  "Taco Day",
        (10,5):  "Apple Betty Day",
        (10,6):  "Noodle Day",
        (10,7):  "Frappe Day",
        (10,8):  "Fluffernutter Day",
        (10,9):  "Dessert Day",
        (10,10): "Angel Food Cake Day",
        (10,11): "Sausage Pizza Day",
        (10,13): "Yorkshire Pudding Day",
        (10,14): "Chocolate Covered Insect Day",
        (10,15): "Mushroom Day",
        (10,16): "Oatmeal Day",
        (10,17): "Pasta Day",
        (10,18): "Chocolate Cupcake Day",
        (10,19): "Seafood Bisque Day",
        (10,20): "Brandied Fruit Day",
        (10,21): "Pumpkin Cheesecake Day",
        (10,22): "Nut Day",
        (10,23): "Boston Cream Pie Day",
        (10,24): "Bologna Day",
        (10,25): "Greasy Foods Day",
        (10,26): "Mincemeat Pie Day",
        (10,27): "Potato Day",
        (10,28): "Chocolate Day",
        (10,29): "Pancake Day",
        (10,30): "Candy Corn Day",
        (10,31): "Caramel Apple Day",
        (11,1):  "French Fried Clam Day",
        (11,2):  "Deviled Egg Day",
        (11,3):  "Sandwich Day",
        (11,4):  "Candy Day",
        (11,5):  "Doughnut Day",
        (11,6):  "Nachos Day",
        (11,7):  "Bittersweet Chocolate with Almonds Day",
        (11,8):  "Harvey Wallbanger Day",
        (11,9):  "Scrapple Day",
        (11,10): "Vanilla Cupcake Day",
        (11,11): "Sundae Day",
        (11,12): "Pizza with the Works Day",
        (11,13): "Indian Pudding Day",
        (11,14): "Guacamole Day",
        (11,15): "Clean Out Your Refrigerator Day",
        (11,16): "Fast Food Day",
        (11,17): "Baklava Day",
        (11,18): "Vichyssoise Day",
        (11,19): "Carbonated Beverage with Caffeine Day",
        (11,20): "Peanut Butter Fudge Day",
        (11,21): "Stuffing Day",
        (11,22): "Cranberry Relish Day",
        (11,23): "Cashew Day",
        (11,24): "Espresso Day",
        (11,25): "Parfait Day",
        (11,26): "Cake Day",
        (11,27): "Bavarian Cream Pie Day",
        (11,28): "French Toast Day",
        (11,29): "Chocolates Day",
        (11,30): "Mousse Day",
        (12,1):  "Eat a Red Apple Day",
        (12,2):  "Fritters Day",
        (12,3):  "Ice Cream Box Day",
        (12,4):  "Cookie Day",
        (12,5):  "Sacher Torte Day",
        (12,6):  "Gazpacho Day",
        (12,7):  "Cotton Candy Day",
        (12,8):  "Brownie Day",
        (12,9):  "Apple Pie Day",
        (12,10): "Lager Day",
        (12,11): "Noodle-Ring Day",
        (12,12): "Ambrosia Day",
        (12,12): "Gingerbread House Day",
        (12,13): "Cocoa Day",
        (12,14): "Bouillabaisse Day",
        (12,15): "Lemon Cupcake Day",
        (12,16): "Chocolate Covered Anything Day",
        (12,17): "Maple Syrup Day",
        (12,18): "Roast Suckling Pig Day",
        (12,19): "Oatmeal Muffin Day",
        (12,20): "Fried Shrimp Day",
        (12,21): "Hamburger Day",
        (12,22): "Date Nut Bread Day",
        (12,23): "Pfeffernusse Day",
        (12,24): "Egg Nog Day",
        (12,25): "Pumpkin Pie Day",
        (12,26): "Candy Cane Day",
        (12,27): "Fruit Cake Day",
        (12,28): "Chocolate Candy Day",
        (12,29): "Pepper Pot Day",
        (12,30): "Bicarbonate Of Soda Day",
        (12,31): "Champagne Day"
    }[(month,day)]


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='shows the food of the days')
    parser.add_argument('--day', default='today', help='starting day, default is today or 1/31')
    parser.add_argument('--interval', default='7', help='number of days to show')
    pargs = parser.parse_args()

    if pargs.day == 'today':
        now = datetime.datetime.now()
        month = now.month
        day = now.day
    else:
        month,day = pargs.day.split('/')
    food_of_day_interval(int(month), int(day), int(pargs.interval))
